name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      composer_require_extra:
        silvershop/core:dev-main
        silverstripe/installer:^6.2.0
